- .github/workflows/checkov-terraform-iac-scan.yml
- .github/workflows/trivy-container-scan.yml
- README-release-please.md
- README-trivy-container-scan.md
> fix
job if condition
-   [ ] New feature (non-breaking change which adds functionality)
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update
-   [ ] Tested the workflow in a repo
Incase the current PR is dependent onto some other PR, please add the link to it.
-   [ ] I have reviewed my code while raising this PR
-   [x] I have added comments to my code, particularly in hard-to-understand areas
-   [x] I have created a new …
> fix(container-scan): job if condition

- .github/pull_request_template.md
- .github/workflows/nodejs-ci.yml
- .github/workflows/pulse-dependencies-analytics.yml
- .github/workflows/pulse-sast-analytics.yml
- README-codium-pr-agent.md
- README-nodejs-ci.md
- README-pulse-dependencies-analytics.md
- README-pulse-sast-analytics.md
- README-trivy-container-scan.md
> Feature: new workflows
- NodeJS-CI
- Pulse dependency analytics
- Pulse SAST analytics
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [x] This change requires a documentation update
-   [ ] Tested the changed workflows in a repo
Incase the current PR is dependent onto some other PR, please add the link to it.
-   [ ] I have reviewed my code while raising this PR
-   [ ] I have added comments to my …
> Feature: nodejs ci, and Pulse analytics made reusable workflow

- README.md
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update
-   [ ] Tested the changed workflows in a repo
Incase the current PR is dependent onto some other PR, please add the link to it.
-   [ ] I …
> fix: setting release verison to 1.6.0

- .github/workflows/nodejs-ci.yml
- .github/workflows/trivy-container-scan.yml
- README-nodejs-ci.md
- README-php-ci.md
- README-trivy-container-scan.md
-   [ ] New feature (non-breaking change which adds functionality)
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update
-   [ ] Tested the changed workflows in a repo
Incase the current PR is dependent onto some other PR, please add the link to it.
-   [ ] I have reviewed my code while raising this PR
-   [x] I have added comments to my code, particularly in hard-to-understand areas
-   [ ] I have created a new README file …
> Fix(container scan): NPM_TOKEN input as docker build arg

- .github/workflows/security-scans.yml
> Fix(dependency scan): report to display suppressed vulnerabilities when there are no vulnerabilities

- .github/workflows/nodejs-ci.yml
- .github/workflows/security-scans.yml
> fix(osv suppression): config.toml file created at runtime, config file from Dockerfile is deprecated and has issue

- .github/workflows/release-please.yml
- README-release-please.md
> feat(release-please): Tag naming automated for HotFix release & regular realase post HF release

- .github/workflows/checkov-terraform-iac-scan.yml
- .github/workflows/codium-pr-agent.yml
- .github/workflows/mobile-nodejs-ci.yml
- .github/workflows/nodejs-ci.yml
- .github/workflows/pulse-sast-analytics.yml
- .github/workflows/security-scans.yml
- .github/workflows/trivy-container-scan.yml
> fix: All the workflow jobs permission revisited and set to minimum

- .github/workflows/checkov-terraform-iac-scan.yml
> feature(iac scan): terraform fmt run on all dir and commits the change to source branch in PR

- .github/workflows/codium-pr-agent.yml
- .github/workflows/mobile-nodejs-ci.yml
- .github/workflows/nodejs-ci.yml
- .github/workflows/php-ci.yml
- .github/workflows/release-please.yml
- .github/workflows/security-scans.yml
- .github/workflows/this-repo-release-please.yml
> fix(all workflows): Job ID and job name are matched to facilitate automation in GitHub checks mandate config

- .github/workflows/security-scans.yml
> chore(license_scan):enhance|redundant error message removed

- .github/workflows/trivy-container-scan.yml
> fix(iac-scan): vulnerability report step getting skipped on vuln. findings in container scan step is now fixed 

- .github/workflows/pulse-sast-analytics.yml
> fix(PX-1602): Pulse SAST branch env arg value ref

- .github/workflows/release-please.yml
- README.md
> feat(release-please): set RELEASE_TYPE default=node

- .github/workflows/release-please.yml
Fix: Release-Please
> error: basename: missing operand
> Fix(release-please): tagging validation step, hotfix tag name slice: error basename: missing operand

- .github/workflows/nodejs-ci.yml
- README-nodejs-ci.md
Added script to send the test coverage report generated to Pulse.
A secret named __PULSE_HAMC_SECRET__  and a variable  __PULSE_URL__ needs to be created on the organization level.
> feat(PX-1850): Composing and Sending test coverage report to Pulse

- .github/workflows/nodejs-ci.yml
> fix(nodejs-ci): made PULSE_HMAC_SECRET as non required secret

- .github/workflows/release-please.yml
- README-nodejs-ci.md
- README-release-please.md
Reverts studiographene/github-action-workflows#61
> Revert "Feat(release-please): option to define target-branch for release creation"

- .github/workflows/release-please.yml
- README-release-please.md
Option to define target branch to create Git release using input `TARGET_BRANCH` and more inputs added
> feat(release-please): option to define target-branch for release creation

- README-checkov-terraform-iac-scan.md
> chore(checkov-terraform-iac-scan): typo in readme example

- .github/workflows/trivy-container-scan.yml
> fix(trivy-scans): scan report is now commented in PR for vulnerabilities

- .github/workflows/nodejs-ci.yml
- .github/workflows/pulse-work-break-down.yml
- README-nodejs-ci.md
> feat(PX-2418): added script to Pulse: Workbreakdown

- .github/workflows/nodejs-ci.yml
> feat(PX-2418): Changed branch ref to master for Work Breakdown action

- .github/workflows/checkov-terraform-iac-scan.yml
> fix(ENB-83 TF IaC Scan): install TF runtime

- .github/workflows/pr-check.yml
> Fix(enb 83): pr check now skips merge commit which would not have conventional commit format

- .github/workflows/security-scans.yml
License scan default whitelisted license additions Unicode-DFS-2016, LGPL-3.0-or-later, ODC-By-1.0
> feat(ENB-83):License scan license additions

- .github/workflows/release-please.yml
- README-release-please.md
Outputs added for Release-Please workflow
> feat(ENB-83 release-please): outputs added
